//
//  MockAquinasModel.swift
//  Aquinas-iOS
//

import Foundation

/// Deterministic preview, test, and fallback behavior. The live environment uses
/// `BackendAquinasModel`, which delegates here only when the local server is unavailable or when
/// a task-specific backend contract has not been implemented yet.
struct MockAquinasModel: AquinasModel {
    func respond(to context: ConversationContext) async -> ModelResponse {
        Self.simulatedResponse
    }

    func compact(_ context: ConversationContext) async -> String {
        let previous = context.compactedContext.map { [$0] } ?? []
        let current = context.transcript.map { block in
            switch block {
            case .text(let text):
                return "Assistant: \(text)"
            case .user(let text, _, _):
                return "User: \(text)"
            }
        }
        let combined = (previous + current).joined(separator: "\n")
        return String(combined.suffix(6_000))
    }

    func defineTerm(_ term: String, in context: ConversationContext) async -> ConceptDefinition {
        try? await Task.sleep(nanoseconds: 1_500_000_000)
        return ConceptDefinition(
            word: term.capitalized,
            partOfSpeech: "noun",
            pronunciation: "| \(term) |",
            meaning: "This concept appears in the response as a key theological or philosophical term. A full definition will be generated by the model in the connected version of the app.",
            example: "Tap 'Inquire Further' to explore \(term.capitalized) in a new conversation."
        )
    }

    func labelSubject(forTitles titles: [String]) async -> String {
        let stopWords: Set<String> = ["the", "and", "of", "to", "in", "a", "an", "is", "for", "on", "with", "from"]
        let words = titles
            .flatMap { $0.lowercased().split(separator: " ") }
            .map { $0.trimmingCharacters(in: .punctuationCharacters) }
            .filter { $0.count > 3 && !stopWords.contains($0) }

        let ranked = Dictionary(grouping: words, by: { $0 })
            .map { ($0.key, $0.value.count) }
            .sorted { $0.1 > $1.1 }
            .prefix(2)
            .map { $0.0.capitalized }

        return ranked.isEmpty ? "Inquiry" : ranked.joined(separator: " ")
    }

    func blendConcepts(_ concepts: [ConceptDefinition], weights: [Double]) async -> ConceptDefinition {
        // Placeholder blend, mirrors today's synchronous placed-midpoint stub
        // (`InsightTreeView.makeMidpointConcept`) — a real implementation would build a
        // "blend these concepts at these weights" prompt from `concepts`/`weights`.
        ConceptDefinition(word: "New Insight", partOfSpeech: "", pronunciation: "", meaning: "", example: "")
    }

    func generateChildren(for concept: ConceptDefinition) async -> [ConceptDefinition] {
        // Placeholder children, mirrors today's inline stub in
        // `InsightTreeViewModel.appendPromotedNodes` — not yet wired into that synchronous
        // placement flow (see its comment) to avoid disturbing the Make Node reveal animation's
        // stable child-ID timing; this seam is ready for whoever connects it.
        (0..<3).map { _ in
            ConceptDefinition(word: "New Insight", partOfSpeech: "", pronunciation: "", meaning: "", example: "")
        }
    }

    // simulatedResponse is temporary prototype content; replace this when the real model is
    // connected. keyTerms mirrors the backend's key_terms shape (MODEL-INTEGRATION.md §3) — plain
    // prose plus the terms to highlight, spliced into `aq://` markup by `ModelResponse.annotatedText`.
    static let simulatedResponse = ModelResponse(
        text: "Thomas Aquinas is one of the most influential figures in western thought. Often referred to as the Doctor Angelicus, he is the primary architect of Thomism THE DIDACHE: THE TEACHING OF THE TWELVE APOSTLES The Didache (pronounced DID-ah-kay) is essentially the first-century 'user manual' for the early Christian church. Derived from the Greek word for 'teaching,' this document was written between 50 AD and 100 AD, providing a rare look at how the earliest Christian communities organized their lives. I. THE TWO WAYS The document opens with a moral framework called 'The Two Ways,' contrasting the Way of Life with the Way of Death. It outlines a strict ethical code, covering everything from communal love to specific social prohibitions. II. RITUAL AND LITURGY The Didache provides the earliest 'how-to' instructions for Christian rituals: • Baptism: Prefers 'living' (running) water, but allows for pouring if necessary. • Fasting: Suggests specific days of the week (Wednesdays and Fridays). • THE Eucharist: Contains some of the oldest recorded prayers for communion. III. CHURCH STRUCTURE It outlines the qualifications for bishops and deacons and provides a fascinating guide on how to distinguish between genuine traveling prophets and those seeking personal gain. HISTORICAL IMPACT Lost for centuries and rediscovered in 1873, the Didache serves as a vital bridge between the New Testament era and the formalized Church of later centuries.",
        keyTerms: [
            KeyTerm(displayText: "Thomism"),
            KeyTerm(displayText: "Didache", contextExcerpt: "APOSTLES The Didache (pronounced"),
            KeyTerm(displayText: "The Two Ways"),
            KeyTerm(displayText: "Baptism"),
            KeyTerm(displayText: "Fasting"),
            KeyTerm(displayText: "Eucharist"),
            KeyTerm(displayText: "traveling prophets")
        ]
    )
}
