//
//  MockAquinasModel.swift
//  Aquinas-iOS
//

import Foundation

/// Deterministic preview and test behavior. Live generation never substitutes this content when
/// the backend is unavailable.
struct MockAquinasModel: AquinasModel {
    func respond(to context: ConversationContext) async -> ModelResponse {
        Self.simulatedResponse
    }

    func compact(_ context: ConversationContext) async -> String {
        let previous = context.compactedContext.map { [$0] } ?? []
        let current = context.transcript.map { block in
            switch block {
            case .text(let text):
                return "Assistant: \(InlineInsightMarkup.plainText(from: text))"
            case .user(let text, _, _):
                return "User: \(text)"
            }
        }
        let combined = (previous + current).joined(separator: "\n")
        return String(combined.suffix(6_000))
    }

    func defineTerm(_ term: String, in context: ConversationContext) async -> ConceptDefinition {
        try? await Task.sleep(nanoseconds: 1_500_000_000)
        return ConceptDefinition(
            word: term.capitalized,
            partOfSpeech: "",
            pronunciation: "",
            meaning: "This concept appears in the response as a key theological or philosophical term. A full definition will be generated by the model in the connected version of the app.",
            example: "",
            context: "The current inquiry"
        )
    }

    func labelSubject(forTitles titles: [String]) async -> String {
        let stopWords: Set<String> = ["the", "and", "of", "to", "in", "a", "an", "is", "for", "on", "with", "from"]
        let words = titles
            .flatMap { $0.lowercased().split(separator: " ") }
            .map { $0.trimmingCharacters(in: .punctuationCharacters) }
            .filter { $0.count > 3 && !stopWords.contains($0) }

        let ranked = Dictionary(grouping: words, by: { $0 })
            .map { ($0.key, $0.value.count) }
            .sorted { $0.1 > $1.1 }
            .prefix(2)
            .map { $0.0.capitalized }

        return ranked.isEmpty ? "Inquiry" : ranked.joined(separator: " ")
    }

    func blendConceptCandidates(
        _ concepts: [ConceptDefinition],
        weights: [Double]
    ) async -> [ConceptDefinition] {
        let weighted = zip(concepts, weights)
            .sorted { $0.1 > $1.1 }
            .map(\.0)
        let ordered = weighted.isEmpty ? concepts : weighted
        let titles = ordered.prefix(2).map(\.word)
        let definitions = ordered
            .map(\.meaning)
            .filter { !$0.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty }

        let baseTitle = titles.isEmpty
            ? "Blended Insight"
            : titles.joined(separator: " and ")
        let baseDefinition = definitions.joined(separator: " ")
        let example = ordered.lazy.map(\.example).first { !$0.isEmpty } ?? ""
        return [
            ("\(baseTitle) Synthesis", baseDefinition),
            (
                "\(baseTitle) Relationship",
                "The selected concepts mutually shape one another. \(baseDefinition)"
            ),
            (
                "\(baseTitle) Implication",
                "A consequence emerges from their relationship. \(baseDefinition)"
            ),
            (
                "\(baseTitle) Distinction",
                "Their shared ground preserves an important distinction. \(baseDefinition)"
            ),
            (
                "\(baseTitle) Application",
                "Their relationship can guide interpretation or action. \(baseDefinition)"
            ),
        ].map { title, definition in
            ConceptDefinition(
                word: title,
                partOfSpeech: "",
                pronunciation: "",
                meaning: definition,
                example: example
            )
        }
    }

    func generateChildren(for concept: ConceptDefinition) async -> [ConceptDefinition] {
        let title = concept.word.trimmingCharacters(in: .whitespacesAndNewlines)
        let nodeTitle = title.isEmpty ? "This Concept" : title
        let sourceDefinition = concept.meaning.trimmingCharacters(
            in: .whitespacesAndNewlines
        )
        let context = sourceDefinition.isEmpty
            ? "\(nodeTitle) can be explored through its foundations, implications, and use."
            : sourceDefinition

        return [
            ConceptDefinition(
                word: "Foundations of \(nodeTitle)",
                partOfSpeech: "",
                pronunciation: "",
                meaning: "The underlying principles that make \(nodeTitle) intelligible. \(context)",
                example: ""
            ),
            ConceptDefinition(
                word: "Implications of \(nodeTitle)",
                partOfSpeech: "",
                pronunciation: "",
                meaning: "The consequences and relationships that follow from \(nodeTitle). \(context)",
                example: ""
            ),
            ConceptDefinition(
                word: "\(nodeTitle) in Practice",
                partOfSpeech: "",
                pronunciation: "",
                meaning: "A concrete application of \(nodeTitle) in judgment or action. \(context)",
                example: concept.example
            ),
        ]
    }

    // simulatedResponse is temporary prototype content; replace this when the real model is
    // connected. keyTerms mirrors the backend's key_terms shape (MODEL-INTEGRATION.md §3) — plain
    // prose plus the terms to highlight, spliced into `aq://` markup by `ModelResponse.annotatedText`.
    static let simulatedResponse = ModelResponse(
        text: "Thomas Aquinas is one of the most influential figures in western thought. Often referred to as the Doctor Angelicus, he is the primary architect of Thomism THE DIDACHE: THE TEACHING OF THE TWELVE APOSTLES The Didache (pronounced DID-ah-kay) is essentially the first-century 'user manual' for the early Christian church. Derived from the Greek word for 'teaching,' this document was written between 50 AD and 100 AD, providing a rare look at how the earliest Christian communities organized their lives. I. THE TWO WAYS The document opens with a moral framework called 'The Two Ways,' contrasting the Way of Life with the Way of Death. It outlines a strict ethical code, covering everything from communal love to specific social prohibitions. II. RITUAL AND LITURGY The Didache provides the earliest 'how-to' instructions for Christian rituals: • Baptism: Prefers 'living' (running) water, but allows for pouring if necessary. • Fasting: Suggests specific days of the week (Wednesdays and Fridays). • THE Eucharist: Contains some of the oldest recorded prayers for communion. III. CHURCH STRUCTURE It outlines the qualifications for bishops and deacons and provides a fascinating guide on how to distinguish between genuine traveling prophets and those seeking personal gain. HISTORICAL IMPACT Lost for centuries and rediscovered in 1873, the Didache serves as a vital bridge between the New Testament era and the formalized Church of later centuries.",
        keyTerms: [
            KeyTerm(displayText: "Thomism"),
            KeyTerm(displayText: "Didache", contextExcerpt: "APOSTLES The Didache (pronounced"),
            KeyTerm(displayText: "The Two Ways"),
            KeyTerm(displayText: "Baptism"),
            KeyTerm(displayText: "Fasting"),
            KeyTerm(displayText: "Eucharist"),
            KeyTerm(displayText: "traveling prophets")
        ]
    )
}
